#!/usr/bin/env python3
"""
Ntel AIR Opcode Extraction Tool

Extracts AIR (Apple Intermediate Representation) opcodes from Metal shader bytecode
for building the translation LUT. Designed to run offline on macOS with Xcode tools.

Typical workflow:
    1. python3 extract_air_opcodes.py shaders/clear_screen.metal build/
    2. Examine build/clear_screen.air dump for opcode patterns
    3. Map hex values to translator functions in NtelTranslationEngine.c
    4. Validate with test_translation_output() in NtelSimulation.c
"""

import subprocess
import sys
import os
import re
import json
from pathlib import Path

def compile_shader(source_path: str, output_dir: str) -> tuple[str, str]:
    """Compile .metal source to .air bytecode using xcrun metal."""
    source = Path(source_path)
    if not source.exists():
        raise FileNotFoundError(f"Shader source not found: {source_path}")
    
    air_path = os.path.join(output_dir, source.stem + ".air")
    metallib_path = os.path.join(output_dir, source.stem + ".metallib")
    
    # Compile to AIR (contains raw bitcode)
    cmd = ["xcrun", "-sdk", "macosx", "metal", "-c", str(source), "-o", air_path]
    subprocess.run(cmd, check=True)
    
    # Create metallib (optional, for reference)
    cmd = ["xcrun", "-sdk", "macosx", "metallib", air_path, "-o", metallib_path]
    subprocess.run(cmd, check=True)
    
    return air_path, metallib_path

def analyze_air_with_llvm(air_path: str) -> str:
    """Dump AIR bitcode using llvm-bcanalyzer."""
    result = subprocess.run(
        ["llvm-bcanalyzer", "-dump", air_path],
        capture_output=True,
        text=True
    )
    return result.stdout

def extract_opcodes_from_dump(dump: str) -> dict:
    """Parse llvm-bcanalyzer output to extract opcode patterns."""
    opcodes = {}
    
    # Pattern: Look for operation names and their hex representations
    # AIR opcodes often appear as named records in the bitcode
    patterns = [
        (r'FUNCTION_CODE\s+([0-9a-fA-F]+)', 'function'),
        (r'OPERAND_CODE\s+([0-9a-fA-F]+)', 'operand'),
        (r'INST_CODE\s+([0-9a-fA-F]+)', 'instruction'),
    ]
    
    for pattern, op_type in patterns:
        matches = re.findall(pattern, dump)
        for m in matches:
            if op_type not in opcodes:
                opcodes[op_type] = []
            opcodes[op_type].append(m)
    
    return opcodes

def generate_lut_entries(opcodes: dict, output_file: str):
    """Generate C LUT entries from extracted opcodes."""
    with open(output_file, 'w') as f:
        f.write("// Auto-generated AIR opcode LUT entries\n")
        f.write("// Generated by extract_air_opcodes.py\n\n")
        
        for op_type, values in opcodes.items():
            f.write(f"// {op_type.upper()} opcodes\n")
            for i, val in enumerate(values[:10]):  # Limit output
                f.write(f"//   Entry {i}: 0x{val}\n")

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 extract_air_opcodes.py <shader.metal> [output_dir]")
        sys.exit(1)
    
    source_path = sys.argv[1]
    output_dir = sys.argv[2] if len(sys.argv) > 2 else "build"
    
    os.makedirs(output_dir, exist_ok=True)
    
    print(f"Compiling {source_path}...")
    air_path, metallib_path = compile_shader(source_path, output_dir)
    
    print(f"Analyzing {air_path}...")
    dump = analyze_air_with_llvm(air_path)
    
    print("Extracting opcodes...")
    opcodes = extract_opcodes_from_dump(dump)
    
    lut_file = os.path.join(output_dir, "air_opcodes_generated.h")
    generate_lut_entries(opcodes, lut_file)
    
    print(f"Generated LUT entries in {lut_file}")
    print(f"AIR file: {air_path}")
    print(f"Metallib: {metallib_path}")

if __name__ == "__main__":
    main()